### ISSUE TITLE
Polishing the design of the site

### ISSUE THREAD

**Issue by Kennu76** [kenigbolo/Chafity#39]
If the requirements are covered and the platform works, then we will make the front-end part more user-friendly

+ The Workflow is there already but the design is somehow raw, not even half baked.
+ Some links get darks on hover etc.. the messages don't look like the given design
+ The main page should have the logo center not a the left side of the screen @Kennu76 ,
+ The dashboard should have more information than they have now,
+ And finally all the actions should have flash messages.

**Comment by FottyM** [comment]
The Workflow is there already but the design is somehow raw, not even half baked.
Some links get darks on hover etc.. the messages don't look like the given design
The main page should have the logo center not a the left side of the screen @Kennu76 ,
The dashboard should have more information than they have now,
and finally all the actions should have flash messages.
