### ISSUE TITLE
Improve the payment workflow

### ISSUE THREAD

**Issue by Kennu76** [kenigbolo/Chafity#40]
- As a user after paying if I make a mistake of reloading the page before I send any message 
- The system asks will ask me to pay again. which is wrong.
- The Javascript behind the payment logic is buggy, all buttons disappear after clicking on one of them.

**Comment by kenigbolo** [comment]
@Kennu76  Add some description to what this task means

**Comment by FottyM** [comment]
+ As a user after paying if I make a mistake of reloading the page before I send any message 
+ The system asks will ask me to pay again. which is wrong.
+ The Javascript behind the payment logic is buggy, all buttons disappear after clicking on one of them.

**Comment by kenigbolo** [comment]
Issue implemented, closing issue
