### ISSUE TITLE
improve admin

### ISSUE THREAD

**Issue by FottyM** [kenigbolo/Chafity#43]
The Admin Dashboard shows thins that it shouldn't like private messages and it doesn't show recent model added like charities, which it should.

**Comment by kenigbolo** [comment]
@FottyM Add some description to what this task means

**Comment by FottyM** [comment]
The Admin Dashboard shows thins that it shouldn't like private messages and it doesn't show recent model added like charities, which it should.
@kenigbolo try to look into it, maybe I ma wrong.

**Comment by kenigbolo** [comment]
@FottyM Showing messages in the Admin panel isn't wrong in my opinion. Doesn't make sense to create a system you do not have any controller over. It's like saying facebook or linkedin would have the messages you send on their platform. For the charities model that I will fix, problem obviously is that I haven't generated admin view for charities yet
