### ISSUE TITLE
improve the search functionality

### ISSUE THREAD

**Issue by FottyM** [kenigbolo/Chafity#44]
### At this point:
+ As a user I can only enter a first name or a last name of another user in the search bar
+ And click on search in order to find the matching user.

### But what I want is:
+ As a user I should be able to start typing characters in the search bar 
+ Then a list of suggestion will be shown as I am typing
+ Then I should be able to click on the matching user straight if his/her name is show on the list
+ Or I can enter the name of a charity organization the see all the users that are related to that charity 
+ And then just pick one and send the money.

**Comment by kenigbolo** [comment]
@FottyM Add some description to what this task means

**Comment by FottyM** [comment]
### At this point:
+ As a user I can only enter a first name or a last name of another user in the search bar
+ And click on search in order to find the matching user.

### But what I want is:
+ As a user I should be able to start typing characters in the search bar 
+ Then a list of suggestion will be shown as I am typing
+ Then I should be able to click on the matching user straight if his/her name is show on the list
+ Or I can enter the name of a charity organization the see all the users that are related to that charity 
+ And then just pick one and send the money.
