### ISSUE TITLE
Modify database migration file

### ISSUE THREAD

**Issue by kenigbolo** [kenigbolo/Chafity#51]
Commands for databases differ. Because we use postgres in production environment and sqlite in development commands for adding boolean to columns differ. This is a bug that needs to be rectified as it results in problems when running `rake db:migrate`

**Comment by FottyM** [comment]
@kenigbolo can me use PG on local machine as well... to avoid the hassle

**Comment by kenigbolo** [comment]
@FottyM Moved this issue. we can as well use PG in development but that might be a problem for the window users. Update the question in the new issue please
