### ISSUE TITLE
add email confirmation link

### ISSUE THREAD

**Issue by Kennu76** [kenigbolo/Chafity#70]
[FR #1](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#1-the-website-offers-the-option-to-sign-up-through-the-default-registration-or-by-making-a-linkedin-account)
[FR #2](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#2-the-website-allows-users-with-a-linkedin-account-to-login)

**Comment by kenigbolo** [comment]
Feature Implemented. Kindly close issue

**Comment by FottyM** [comment]
@kenigbolo and this one too

**Comment by kenigbolo** [comment]
Issue implemented, closing issue
