### ISSUE TITLE
welcome email automation

### ISSUE THREAD

**Issue by Kennu76** [kenigbolo/Chafity#71]
after a user has confirmed his email aka verified that he is a legitimate user then he recieves an email that welcomes him to Chafity and the email gives him a few tips on how to begin using the site
[FR #1](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#1-the-website-offers-the-option-to-sign-up-through-the-default-registration-or-by-making-a-linkedin-account)
[FR #2](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#2-the-website-allows-users-with-a-linkedin-account-to-login)

**Comment by kenigbolo** [comment]
Feature implemented, closing issue
