### ISSUE TITLE
payment confirmation by email

### ISSUE THREAD

**Issue by Kennu76** [kenigbolo/Chafity#72]
When a user pays with a credit card and the payment is confirmed then the user gets an email that says that the money went through
[FR #1](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#1-the-website-offers-the-option-to-sign-up-through-the-default-registration-or-by-making-a-linkedin-account)
[FR #2](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#2-the-website-allows-users-with-a-linkedin-account-to-login)

**Comment by kenigbolo** [comment]
Feature Implemented, closing issue
