### ISSUE TITLE
Add languages spoken field to User profile

### ISSUE THREAD

**Issue by kenigbolo** [kenigbolo/Chafity#81]
The languages spoken by a user should be displayed on their profile. If the user signs-up via linkedin then we grab the fields from their linkedin profile

**Comment by kenigbolo** [comment]
This issue requires approval from Linkedin, one which we do not currently have. For reference see this stackoverflow post [here](http://stackoverflow.com/questions/30211460/linkedin-oauth-exception-scope-not-authorized-r-fullprofile)

**Comment by Kennu76** [comment]
[FR#3](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#3-the-website-allows-users-to-search-for-other-users-through-the-search-tool-users-can-be-searched-by-name-or-company-and-search-can-be-filtered-by-influencers-uc3-issue13)
